### ISSUE TITLE
Affichage logo DOI à côté des ressources

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss#176]
Ca serait bien d'afficher le logo DOI devant chaque ressource dans la page qui liste les ressources d'un corpus.

Ex : https://pangloss.cnrs.fr/corpus/Japhug

On mettrait le logo DOI juste avant "Type" en ajoutant une colonne.
En cliquant sur le logo DOI on pourrait (comme dans la page d'une ressource) copier le DOI de la ressource en question.

**Comment by EdouardSombie** [comment]
Salut !
je m'en occupe cette semaine.

**Comment by sguillaume** [comment]
Merci :)
C'est pas super pressé mais ça sera bien utile !

**Comment by EdouardSombie** [comment]
C'est fait !

**Comment by sguillaume** [comment]
Parfait pour moi !
