### ISSUE TITLE
bogue dans les liens vers les documents depuis une page de résultats de recherche

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss#179]
Les liens vers les ressources (depuis une page Corpus, ou depuis une page de résultats de recherche) donnent une erreur 404. 

- Depuis une page de résultats de recherche, comme celle-ci : 
https://pangloss.cnrs.fr/search?s=Tai%20Yo
ou celle-ci : 
https://pangloss.cnrs.fr/search?s=yongning

- Depuis une page corpus, comme celle-ci : 
https://pangloss.cnrs.fr/corpus/Tai%20Don?lang=fr&mode=normal

Ces liens sont du type : 
`https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-5a18fdd0-18dd-3295-a691-9f5090594e25&corpus=
`
Il y a quelque chose à modifier dans le lien, non ? Dès lors qu'on retranche `&corpus=`, ça marche.

Les liens depuis le carrousel, qui ne comportent pas cette mention `&corpus=`, marchent sans problème.

**Comment by alexis-michaud** [comment]
Bravo pour la remise à flots dans l'heure ! :+1:

**Comment by EdouardSombie** [comment]
Re-salut !
J'ai consolidé le mécanisme qui permet de précisé dans l'url à quel corpus une ressource est rattachée.
Cela a réglé le problème soulevé tout à l'heure.
J'en ai profité pour ajouter un système de formatage de l'url qui nous donne un résultat de ce type: 
![Capture d’écran 2021-07-11 à 13 25 49](https://user-images.githubusercontent.com/66474742/125193206-8b27d480-e24b-11eb-8902-e0f2dfc80f0c.png)

J'ai fait plusieurs tests, mais il faudra vérifier qu'il n'y a pas d'effets indésirables :)
A bientôt et bon dimanche !

**Comment by alexis-michaud** [comment]
Un souci, c'est que la liste des langues n'apparaît plus, dans la page "Corpus".

**Comment by EdouardSombie** [comment]
Salut Alexis,
Il faut rafraichir ton cache navigateur.
J'ai oubli de le préciser hier :)
Bonne journée
