### ISSUE TITLE
DOI non affiché pour une ressource : "Mother's Birthday" (langue : na)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss#186]
Pas de DOI associé qui apparaisse dans la liste des ressources : le bouton "DOI" n'apparaît pas pour cette ressource.
![image](https://user-images.githubusercontent.com/6072524/162236131-64291265-952b-4265-8962-cc11774a5784.png)

Sur la page de consultation, le bouton "DOI" apparaît mais la valeur n'est pas présente : 
![image](https://user-images.githubusercontent.com/6072524/162235114-bc40309f-8134-4ee1-83ee-1d5ab0fb7510.png)

Voici [un lien vers la page de consultation](https://pangloss.cnrs.fr/corpus/show?corpus=Yongning_Na&lang=fr&mode=normal&oai_primary=cocoon-8c729359-ac07-46bd-b293-59ac07b6bdb5&oai_secondary=cocoon-0dd84155-14a7-4115-9841-5514a781159a&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=ortho&optionSentenceTranslations=zh&optionWordTranscriptions=&optionWordTranslations=&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false).

Voici les identifiants attribués par Cocoon pour la ressource audio : 

ark:/87895/1.8-1141110
doi:10.34847/cocoon.8c729359-ac07-46bd-b293-59ac07b6bdb5
oai:crdo.vjf.cnrs.fr:cocoon-8c729359-ac07-46bd-b293-59ac07b6bdb5

**Comment by EdouardSombie** [comment]
Tous les doi semblent apparaitre sur ton lien...

**Comment by alexis-michaud** [comment]
@EdouardSombie l'étiquette "bogue" a pu t'inquiéter, mais ne te mets pas martel en tête : ça concerne simplement la génération des identifiants DOIs, c'est @sguillaume qui gère ça. La ressource en question ("Mother's Birthday") n’avait pas de DOI affecté (elle et ses ressources associées). Séverine a ajouté ces ressources parmi le prochain lot qui bénéficiera d'une création de DOIs. Maintenant ce n'est plus qu'une question de temps : ça apparaîtra en ligne sous quinzaine. 
Et tout est pour le mieux !
Pour plus de sûreté, laissons tout de même le ticket ouvert jusqu'à ce que l'affichage corrigé soit effectif et visible.

**Comment by EdouardSombie** [comment]
👍

**Comment by alexis-michaud** [comment]
DOI créé et ajouté, merci @sguillaume
